version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: student-attendance-db
    environment:
      POSTGRES_DB: student_attendance_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: