services:
  postgres:
    image: postgres:15
    container_name: student-attendance-db
    environment:
      POSTGRES_DB: student_attendance_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d student_attendance_dev"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  migrations:
    build: .
    container_name: student-attendance-migrations
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: student_attendance_dev
      DB_USER: postgres
      DB_PASSWORD: password123
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    command: sh -c "npm run migrate"

  app:
    build: .
    container_name: student-attendance-app
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: student_attendance_dev
      DB_USER: postgres
      DB_PASSWORD: password123
      JWT_SECRET: supersecretjwtkey
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    networks:
      - app-network
    command: npm run dev

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge